# Generated by Django 4.1.3 on 2022-11-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('excutable_name', models.TextField()),
                ('image_file', models.ImageField(upload_to='screenshots')),
                ('screenshot_type', models.TextField(choices=[('META', 'META'), ('IMAGE', 'IMAGE'), ('NSFW', 'NSFW'), ('NSFW_IMAGE', 'NSFW_IMAGE'), ('NSFW_META', 'NSFW_META')], default='META')),
                ('is_nsfw', models.BooleanField(blank=True, null=True)),
                ('is_profane', models.BooleanField(blank=True, null=True)),
                ('nsfw_detection', models.JSONField(blank=True, default=list, help_text='NSFW detection results', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
