# Generated by Django 4.1.3 on 2022-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("excutable_name", models.TextField()),
                ("base64_image", models.TextField()),
                (
                    "for_processing",
                    models.BooleanField(
                        default=True, help_text="Run NSFW detection on this screenshot"
                    ),
                ),
                ("is_nsfw", models.BooleanField(default=False)),
                ("is_profane", models.BooleanField(default=False)),
                (
                    "bounding_boxes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Bounding boxes for the images in the screenshot",
                        null=True,
                    ),
                ),
                (
                    "nsfw_detection",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="NSFW detection results",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
