# Generated by Django 4.1.3 on 2022-11-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenshot",
            name="for_processing",
        ),
        migrations.AddField(
            model_name="screenshot",
            name="screenshot_type",
            field=models.TextField(
                choices=[
                    ("META", "META"),
                    ("IMAGE", "IMAGE"),
                    ("NSFW", "NSFW"),
                    ("NSFW_IMAGE", "NSFW_IMAGE"),
                    ("NSFW_META", "NSFW_META"),
                ],
                default="META",
            ),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="base64_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
