# Generated by Django 4.1.3 on 2022-11-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_screenshot_for_processing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenshot",
            name="bounding_boxes",
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="is_nsfw",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="screenshot",
            name="is_profane",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
