# Generated by Django 4.1.3 on 2022-11-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_screenshot_bounding_boxes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Heartbeat",
            fields=[
                (
                    "username",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
