# Generated by Django 4.1.3 on 2022-11-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_heartbeat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Heartbeat",
        ),
    ]
