# Generated by Django 4.1.3 on 2022-11-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='binary_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
