# Generated by Django 4.1.3 on 2022-11-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_screenshot_binary_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='binary_image',
        ),
    ]
