# Generated by Django 4.1.1 on 2022-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_nsfw',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
