# Generated by Django 4.1.1 on 2022-09-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep_app', '0003_image_parent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='parent_image',
        ),
        migrations.AddField(
            model_name='image',
            name='keep',
            field=models.BooleanField(default=False),
        ),
    ]
