# Generated by Django 4.1.1 on 2022-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creep_app', '0004_remove_image_parent_image_image_keep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('is_nsfw', models.BooleanField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=200)),
                ('exec_name', models.CharField(max_length=200)),
                ('keep', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
