# Generated by Django 4.1.1 on 2022-09-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("creep_app", "0005_screenshot_delete_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screenshot",
            name="keep",
        ),
    ]
