# Generated by Django 4.1.1 on 2022-09-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creep_app", "0006_remove_screenshot_keep"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="keep",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "screenshots",
                    models.ManyToManyField(
                        related_name="alerts", to="creep_app.screenshot"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
