# Generated by Django 4.1.1 on 2022-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creep_app", "0007_screenshot_keep_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="screenshot",
            name="alerted",
            field=models.BooleanField(default=False),
        ),
    ]
