# Generated by Django 4.1.1 on 2022-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creep_app", "0008_screenshot_alerted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gmail_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Config",
            },
        ),
    ]
