# Generated by Django 4.0.4 on 2022-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processedScreenCaptures/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('input_name', models.TextField(default='', max_length=500)),
                ('skin_rating', models.FloatField(blank=True, default=0, null=True)),
                ('nsfw_rating', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rawScreenCaptures/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('input_name', models.TextField(default='', max_length=500)),
                ('is_proccessed', models.BooleanField(default=False)),
            ],
        ),
    ]
