# Generated by Django 4.0.4 on 2022-05-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_alter_processedscreencapture_nsfw_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedscreencapture',
            name='nsfw_rating',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processedscreencapture',
            name='skin_rating',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
