# Generated by Django 4.0.4 on 2022-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_alter_processedscreencapture_nsfw_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedscreencapture',
            name='nsfw_rating',
        ),
        migrations.RemoveField(
            model_name='processedscreencapture',
            name='skin_rating',
        ),
        migrations.AddField(
            model_name='processedscreencapture',
            name='is_safe',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='processedscreencapture',
            name='is_unsafe',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='processedscreencapture',
            name='skin_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='processedscreencapture',
            name='skin_pixels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedscreencapture',
            name='total_pixels',
            field=models.IntegerField(default=0),
        ),
    ]
