# Generated by Django 4.0.4 on 2022-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_remove_processedscreencapture_nsfw_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rawScreenCaptures/')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('input_name', models.TextField(default='', max_length=500)),
                ('is_proccessed', models.BooleanField(default=False)),
                ('skin_percentage', models.FloatField(blank=True, null=True)),
                ('average_safe', models.FloatField(blank=True, null=True)),
                ('average_unsafe', models.FloatField(blank=True, null=True)),
                ('max_unsafe', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedScreenCapture',
        ),
        migrations.DeleteModel(
            name='RawScreenCapture',
        ),
    ]
