# Generated by Django 4.0.4 on 2022-05-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_screencapture_delete_processedscreencapture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screencapture',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
    ]
