# Generated by Django 4.0.4 on 2022-05-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_screencapture_is_parsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='screencapture',
            name='is_thresholded',
            field=models.BooleanField(default=False),
        ),
    ]
