# Generated by Django 4.0.4 on 2022-05-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_screencapture_is_thresholded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screencapture',
            name='average_unsafe',
        ),
        migrations.RemoveField(
            model_name='screencapture',
            name='max_unsafe',
        ),
    ]
