# Generated by Django 4.0.4 on 2022-05-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_remove_screencapture_average_unsafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screencapture',
            name='image',
            field=models.ImageField(upload_to='screenCaptures/'),
        ),
    ]
