name: CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest


    steps:
      # Checkout the repository
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      # Checkout the LFS files
      - name: Checkout LFS Files
        run: git lfs checkout

      # Pull the LFS files
      - name: Pull LFS objects
        run: git lfs pull

      # Install python 3.10
      - name: Install Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      # Print python version
      - name: Print Python version
        run: python -c "import sys; print(sys.version)"
      
      # Create and activate venv | Installed reqs | Package
      - name: Create and activate venv
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          ./pyinstaller.ps1
      


