name: CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest


    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          lfs: true
      
      - name: Pull LFS objects
        run: git lfs pull

      - name: Run a one-line script
        run: python

