# Manual and On Release
on:
  workflow_dispatch:
  release:
      types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      # Check-out repository
      - uses: actions/checkout@v3
      
      # Echo
      - run: echo ${GITHUB_WORKSPACE}
      
          
          
  